### ISSUE TITLE
EDCE exception

### ISSUE THREAD

**Issue by wiz0floyd** [BeTeK/EliteDB#2]
In options when testing the EDCE connection there's an "Error 2: No such file or directory" When running setup.py in it's own command line, the error is in line 150, "Cannot find file requests\cacert.pem"

I'm running from the source downloaded around 11pm on 6/17/2015

**Comment by BeTeK** [comment]
Have you got requests installed? Also there seem to be problems with 64 bit version python since it puts that file in different location than 32 bit. Just copy it under site packages

**Comment by shole** [comment]
Yea, I had this exact same issue with x64 python on windows.
'requests' installed itself at C:\Python34\Lib\site-packages\requests-2.7.0-py3.4.egg\requests
I just copied it to C:\Python34\Lib\site-packages\requests
