### ISSUE TITLE
Single commodity Loop Routes

### ISSUE THREAD

**Issue by wiz0floyd** [BeTeK/EliteDB#3]
So I'm getting some bad loop routes right now. Not sure if it's just an issue caused by bad data coming in from eddn or something in the search that needs to be blacklisted. Basically I'm getting a lot of loops coming up that show up as ferrying Gold between two stations in the same system. See attached.
![capture](https://cloud.githubusercontent.com/assets/12740829/8734599/102795f6-2bd9-11e5-9f26-978a1033647d.PNG)

NINJA EDIT: It appears that it's getting caused by stations with 0 demand for an item having a high price in EDDN, for example Palladium in the first line has 0 demand.

**Comment by shole** [comment]
Thanks for mentioning this.
I was able to reproduce this and there is something very wrong with the local database.
Deleting EliteMerchantList.sqlite file fixed the issue.

**Comment by shole** [comment]
found it
SET exportPrice=exportPrice
_facepalm_
